{% set name = "owa-msgs" %}
{% set version = "0.4.0" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/owa_msgs-{{ version }}.tar.gz
  sha256: 119a0dd10189897b8641b45212362a9e77d1aaeb21005111cda1bf1738b80422

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - owa-core
    - pydantic >=2.0.0
    - annotated-types

test:
  imports:
    - owa.msgs
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/open-world-agents/open-world-agents
  summary: Core message definitions for Open World Agents
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - MilkClouds
